/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionMenu: typeof import('./src/components/AccordionMenu.vue')['default']
    Avaliacao: typeof import('./src/components/Avaliacao.vue')['default']
    AvaliacaoFormulario: typeof import('./src/components/AvaliacaoFormulario.vue')['default']
    CardCadastro: typeof import('./src/components/CardCadastro.vue')['default']
    ClassificacaoLesao: typeof import('./src/components/Lesao/ClassificacaoLesao.vue')['default']
    CoberturasSelecao: typeof import('./src/components/CoberturasSelecao.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputDados: typeof import('./src/components/InputDados.vue')['default']
    InputElemento: typeof import('./src/components/InputElemento.vue')['default']
    InputString: typeof import('./src/components/InputString.vue')['default']
    LocalizacaoLesao: typeof import('./src/components/Lesao/LocalizacaoLesao.vue')['default']
    MenuNavegacao: typeof import('./src/components/MenuNavegacao.vue')['default']
    Orientacoes: typeof import('./src/components/Orientacoes.vue')['default']
    Rodape: typeof import('./src/components/Rodape.vue')['default']
    SituacaoLesao: typeof import('./src/components/Lesao/SituacaoLesao.vue')['default']
  }
}
