/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionMenu: typeof import('./src/components/AccordionMenu.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    Avaliacao: typeof import('./src/components/Avaliacao.vue')['default']
    AvaliacaoFormulario: typeof import('./src/components/AvaliacaoFormulario.vue')['default']
    CadastroProfissional: typeof import('./src/components/CadastroProfissional.vue')['default']
    CardCadastro: typeof import('./src/components/CardCadastro.vue')['default']
    ClassificacaoLesao: typeof import('./src/components/Lesao/ClassificacaoLesao.vue')['default']
    CoberturasSelecao: typeof import('./src/components/CoberturasSelecao.vue')['default']
    FindCoberturas: typeof import('./src/components/FindCoberturas.vue')['default']
    FindLesoeByPaciente: typeof import('./src/components/FindLesoeByPaciente.vue')['default']
    FindPaciente: typeof import('./src/components/FindPaciente.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputDados: typeof import('./src/components/InputDados.vue')['default']
    InputElemento: typeof import('./src/components/InputElemento.vue')['default']
    InputString: typeof import('./src/components/InputString.vue')['default']
    LocalizacaoLesao: typeof import('./src/components/Lesao/LocalizacaoLesao.vue')['default']
    MenuNavegacao: typeof import('./src/components/MenuNavegacao.vue')['default']
    Orientacoes: typeof import('./src/components/Orientacoes.vue')['default']
    RelatorioCurativoId: typeof import('./src/components/Relatorios/RelatorioCurativoId.vue')['default']
    RelatorioPorLesao: typeof import('./src/components/Relatorios/RelatorioPorLesao.vue')['default']
    RelatorioPorPaciente: typeof import('./src/components/Relatorios/RelatorioPorPaciente.vue')['default']
    RelatorioPorPacientePorData: typeof import('./src/components/Relatorios/RelatorioPorPacientePorData.vue')['default']
    RelatorioPorProfissional: typeof import('./src/components/Relatorios/RelatorioPorProfissional.vue')['default']
    Rodape: typeof import('./src/components/Rodape.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SituacaoLesao: typeof import('./src/components/Lesao/SituacaoLesao.vue')['default']
  }
}
